// Code generated by `bridra generate` from schema/bridra.json. DO NOT EDIT.

package contracts

const (
	RouteGroupSystem   = "system"
	RouteGroupGreeting = "greeting"

	MethodSystemHealth       = "system.health"
	RouteActionSystemHealth  = "health"
	MethodGreetingHello      = "greeting.hello"
	RouteActionGreetingHello = "hello"
)
