// Code generated by `bridra generate` from schema/bridra.json. DO NOT EDIT.

package responses

type HealthResponse struct {
	Status           string `json:"status"`
	FrameworkVersion string `json:"frameworkVersion"`
	ProtocolVersion  int    `json:"protocolVersion"`
	Runtime          string `json:"runtime"`
	Architecture     string `json:"architecture"`
}

type GreetingResponse struct {
	Message   string `json:"message"`
	ServedBy  string `json:"servedBy"`
	Timestamp string `json:"timestamp"`
}
