// Code generated by `bridra generate` from schema/bridra.json. DO NOT EDIT.

package requests

import (
	"strings"

	"github.com/cluion/bridra/backend/framework"
)

type GreetingProfileRequest struct {
	Nickname string `json:"nickname"`
}

func (GreetingProfileRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[GreetingProfileRequest](payload)
}

func (request *GreetingProfileRequest) Normalize() {
	request.Nickname = strings.TrimSpace(request.Nickname)
}

var greetingProfileRequestRules = framework.NewRuleRegistry[GreetingProfileRequest](
	framework.ForField(
		"nickname",
		func(request GreetingProfileRequest) string { return strings.TrimSpace(request.Nickname) },
		framework.MinLength(1, "Nickname must be at least 1 character."),
		framework.MaxLength(32, "Nickname must be 32 characters or fewer."),
	),
)

func (request GreetingProfileRequest) Validate() error {
	request.Normalize()
	return greetingProfileRequestRules.Validate(request)
}

type HelloRequest struct {
	Name    string                  `json:"name"`
	Tone    *string                 `json:"tone,omitempty"`
	Profile *GreetingProfileRequest `json:"profile,omitempty"`
}

func (HelloRequest) ValidatePayload(payload []byte) error {
	return framework.ValidateRequestPayload[HelloRequest](payload)
}

func (request *HelloRequest) Normalize() {
	request.Name = strings.TrimSpace(request.Name)
	if request.Profile != nil {
		request.Profile.Normalize()
	}
}

var helloRequestRules = framework.NewRuleRegistry[HelloRequest](
	framework.ForField(
		"name",
		func(request HelloRequest) string { return strings.TrimSpace(request.Name) },
		framework.MinLength(1, "Name must be at least 1 character."),
		framework.MaxLength(64, "Name must be 64 characters or fewer."),
	),
	framework.ForField(
		"tone",
		func(request HelloRequest) *string { return request.Tone },
		framework.Optional(framework.OneOf("Tone must be one of: friendly, formal.", "friendly", "formal")),
	),
	framework.OptionalNestedField(
		"profile",
		func(request HelloRequest) *GreetingProfileRequest { return request.Profile },
	),
)

func (request HelloRequest) Validate() error {
	request.Normalize()
	return helloRequestRules.Validate(request)
}
